---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sitevplq/act-edu-crm-production/
    - /bin/cp -R .next $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp next.config.js $DEPLOYPATH
