import "./globals.css";
import QueryProvider from "@/providers/QueryProvider";

export const metadata = {
  title: "ACT Education CRM",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
