import {
  Building2,
  Tag,
  CreditCard,
  UserCog,
  Workflow,
  Mail,
  FileText,
  Phone,
  FileInput,
  Settings,
  Database,
  UserCheck,
  Code,
} from "lucide-react";

export const settingsNavigation = [
  {
    id: "preferences",
    label: "Preferences",
    icon: Settings,
    description: "Your account, company and general preferences.",
    component: "PreferencesContent",
  },
  {
    id: "tag-management",
    label: "Tag Management",
    icon: Tag,
    description: "Manage all your tags.",
    component: "TagManagementContent",
  },
  // {
  //   id: "subscription-billing",
  //   label: "Subscription & Billing",
  //   icon: CreditCard,
  //   description: "Your payment and billing details.",
  //   component: "SubscriptionBillingContent",
  // },
  {
    id: "accounts",
    label: "Accounts",
    icon: UserCog,
    description: "Your invoice and tax settings.",
    component: "AccountsContent",
  },
  {
    id: "workflows",
    label: "Workflows",
    icon: Workflow,
    description: "Manage your workflows.",
    component: "WorkflowsContent",
  },
  {
    id: "email",
    label: "Email",
    icon: Mail,
    description: "Manage your company email address.",
    component: "EmailContent",
  },
  {
    id: "templates",
    label: "Templates",
    icon: FileText,
    description: "Manage your email and SMS templates.",
    component: "TemplatesContent",
  },
  {
    id: "phone-settings",
    label: "Phone Settings",
    icon: Phone,
    description: "Manage your conversation through SMS text messages.",
    component: "PhoneSettingsContent",
  },
  {
    id: "lead-forms",
    label: "Lead Forms",
    icon: FileInput,
    description: "Manage your Lead Form settings.",
    component: "LeadFormsContent",
  },
  {
    id: "advanced-automation",
    label: "Advanced Automation Settings",
    icon: Code,
    description: "Manage your automation settings.",
    component: "AdvancedAutomationContent",
  },
  {
    id: "custom-fields",
    label: "Custom Fields",
    icon: Settings,
    description: "Manage your custom fields.",
    component: "CustomFieldsContent",
  },
  {
    id: "general",
    label: "General",
    icon: Settings,
    description: "Manage your general settings.",
    component: "GeneralContent",
  },
  {
    id: "data-import",
    label: "Data Import",
    icon: Database,
    description: "Manage your database imports.",
    component: "DataImportContent",
  },
  {
    id: "office-check-in",
    label: "Office Check-In",
    icon: UserCheck,
    description: "Manage your company office Check-In settings.",
    component: "OfficeCheckInContent",
  },
  {
    id: "api-integrations",
    label: "API & Integrations",
    icon: Code,
    description: "Manage access tokens & Integrate apps.",
    component: "ApiIntegrationsContent",
  },
];